from langchain_core.messages import SystemMessage, HumanMessage
from langchain_google_genai import ChatGoogleGenerativeAI

from src.retriever import load_vectorstore
from src.bm25_retriever import load_documents, build_bm25
from src.hybrid_retriever import hybrid_retrieve
from src.reranker import load_reranker
from src.context_builder import build_context, print_context

from dotenv import load_dotenv

load_dotenv()
# ============================================================
# SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = """
You are a document question-answering assistant.

Your job is to answer the user's question using ONLY the provided
document context.

Rules:

1. Use only information present in the provided context.

2. Do not use outside knowledge.

3. If the answer cannot be found in the context, say:
   "The provided document context does not contain enough information
   to answer this question."

4. Cite the source blocks used in the answer.

Example citation:
[SOURCE 1]

5. If multiple sources support the answer, cite all relevant sources.

Example:
[SOURCE 1] [SOURCE 3]

6. Do not invent page numbers, sections, equations, facts, or citations.

7. Keep the answer clear and concise while explaining technical concepts
when necessary.

8. For mathematical equations, use LaTeX.
   Use $$ ... $$ for standalone/display equations.
   Use $ ... $ only for short mathematical expressions inside sentences.

For standalone mathematical equations, always use display LaTeX
with $$ ... $$ on separate lines.

Do not put standalone equations inside bullet points.
"""


# ============================================================
# BUILD MESSAGES
# ============================================================

def build_messages(query: str, context: str):
    """
    Build the messages that will be sent to the LLM.

    Parameters
    ----------
    query : str
        The user's question.

    context : str
        The retrieved document context created by context_builder.py.

    Returns
    -------
    list
        LangChain messages containing:
        - system instructions
        - user question
        - document context
    """

    system_message = SystemMessage(
        content=SYSTEM_PROMPT
    )

    human_message = HumanMessage(
        content=f"""
QUESTION:

{query}


DOCUMENT CONTEXT:

{context}


ANSWER:
"""
    )

    return [
        system_message,
        human_message,
    ]


# ============================================================
# GENERATE ANSWER
# ============================================================

def generate_answer(llm, query: str, context: str) -> str:
    """
    Generate an answer using any LangChain-compatible chat model.

    Example models that can later be passed here:

    ChatOpenAI
    ChatGoogleGenerativeAI
    ChatOllama
    etc.

    Parameters
    ----------
    llm
        A LangChain-compatible chat model.

    query : str
        User question.

    context : str
        Context produced by context_builder.py.

    Returns
    -------
    str
        Final answer generated by the model.
    """

    if not query.strip():
        raise ValueError("Query cannot be empty.")

    if not context.strip():
        return (
            "The provided document context does not contain enough "
            "information to answer this question."
        )

    messages = build_messages(
        query=query,
        context=context,
    )

    response = llm.invoke(messages)

    content = response.content

    if isinstance(content, list):
        text_parts = []

        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(item.get("text", ""))

        return "\n".join(text_parts).strip()

    return str(content).strip()


def load_llm():
    """
    Create and return the Gemini chat model.
    """

    llm = ChatGoogleGenerativeAI(
        model="gemini-3.5-flash",
        temperature=0,
    )

    print("Gemini LLM loaded successfully.")

    return llm

# ============================================================
# RAG PIPELINE
# ============================================================

def load_rag_components():

    print("Loading RAG components...")

    vectorstore = load_vectorstore()

    documents = load_documents()

    bm25 = build_bm25(documents)

    reranker = load_reranker()

    llm = load_llm()

    print("All RAG components loaded successfully.")

    return {
        "vectorstore": vectorstore,
        "documents": documents,
        "bm25": bm25,
        "reranker": reranker,
        "llm": llm,
    }


def ask_rag(
    components,
    query: str,
):
    """
    Run the complete RAG pipeline.

    Question
        ↓
    Hybrid Retrieval
        ↓
    RRF
        ↓
    Reranking
        ↓
    Context Building
        ↓
    Gemini
        ↓
    Answer
    """

    if not query.strip():
        raise ValueError("Query cannot be empty.")

    # --------------------------------------------------------
    # 1. Hybrid Retrieval
    # --------------------------------------------------------

    candidates = hybrid_retrieve(
        vectorstore=components["vectorstore"],
        bm25=components["bm25"],
        documents=components["documents"],
        query=query,
        k=10,
        dense_k=10,
        bm25_k=10,
    )

    # --------------------------------------------------------
    # 2. Reranking
    # --------------------------------------------------------

    pairs = [
        [query, candidate["document"].page_content]
        for candidate in candidates
    ]

    reranker_scores = components["reranker"].predict(pairs)

    scored_candidates = []

    for candidate, score in zip(candidates, reranker_scores):

        result = candidate.copy()

        result["reranker_score"] = float(score)

        scored_candidates.append(result)

    scored_candidates.sort(
        key=lambda result: result["reranker_score"],
        reverse=True,
    )

    final_results = scored_candidates[:5]

    # --------------------------------------------------------
    # 3. Build Context
    # --------------------------------------------------------

    context = build_context(
        final_results,
        max_chars=12000,
    )

    # --------------------------------------------------------
    # 4. Generate Answer
    # --------------------------------------------------------

    answer = generate_answer(
        llm=components["llm"],
        query=query,
        context=context,
    )

    return {
        "answer": answer,
        "sources": final_results,
    }


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    components = load_rag_components()

    query = "What is positional encoding and why is it needed?"

    result = ask_rag(
        components=components,
        query=query,
    )

    print("\n" + "=" * 80)
    print("FINAL RAG ANSWER")
    print("=" * 80)

    print(result["answer"])

    print("\n" + "=" * 80)
    print("SOURCES")
    print("=" * 80)

    for source in result["sources"]:

        document = source["document"]

        print(
            f"Chunk: {document.metadata.get('chunk_id')} | "
            f"Page: {document.metadata.get('pages')} | "
            f"Section: {document.metadata.get('section_path')}"
        )

    print("=" * 80)